
rule-providers:
  my-rules:
    type: http
    behavior: classical
    url: "https://api.leiting.io/api/v1/client/subscribe?token=21685fd3cebb9f2882d9b9a639db2bfe"
    path: ./ruleset.yaml
    interval: 3600

rules:
  - RULE-SET,my-rules,Proxy
