
proxy-providers:
  myprovider:
    type: http
    url: "https://api.leiting.io/api/v1/client/subscribe?token=21685fd3cebb9f2882d9b9a639db2bfe"
    interval: 3600
    health-check:
      enable: true
      url: "http://www.gstatic.com/generate_204"
      interval: 3600
    path: ./myprovider.yaml
    filter: "!香港,!HK"

proxy-groups:
  - name: Proxies
    type: select
    use:
      - myprovider
